//@# DNA Replication
//@
//@```

// Glucose Metabolism:
protein Glycolysis(glucose + 2 Pi + 2 ADP + 2 NAD --> 2 pyruvate + 2 ATP + 2 NADH + 2 H + 2 H2O, kcat=9.51e28, KM=1e29 uM);

protein pyruvateDehydrogenase(pyruvate + NAD + CoA --> acetylCoA + CO2 + NADH + H, kcat=6.8e19, KM=1e20 uM);

protein TCACycle(acetylCoA + 3 NAD + FAD + ADP + Pi + 2 H2O --> 2 CO2 + 3 NADH + FADH2 + ATP + 2 H + CoA, kcat=5.19e19, KM=1e20 uM);

// Oxidative Phosphorylation:
protein ElectronTransportChain(2 NADH + O2 + 2 H --> 2 H2O + 2 NAD, kcat=8.18e37, KM=1e38 uM);

protein ATPSynthase(ADP + Pi + H --> ATP + H2O, kcat=4.72e7, KM=1e6 uM);

// Set constant and variable concentrations:
//glucose[:] = 0.5 mM;
H2O[:] = 8 M, O2[:] = 5 mM, CO2[:] = 0 mM;
Pi = 5 mM, ADP = 0.17 mM, FAD = 2 mM, NAD = 2.6 mM, NADH = 83 uM, ATP = 5.5 mM, CoA = 2.0 mM;

// Initial conditions for enzymes
Glycolysis = 0.32uM, pyruvateDehydrogenase = 0.48uM, TCACycle = 0.8uM, ElectronTransportChain = 1uM, ATPSynthase = 1uM;

// Regenerate Metabolites:
protein FADRegen(FADH2 --> FAD, kcat=9e5, KM=1);
protein NADRegen(NADH --> NAD, kcat=2e7, KM=1);
//protein ATPRegen(ATP --> ADP + Pi, kcat=1.5e6, KM=1);

// Initial conditions for regeneration
FADRegen = 1uM, ATPRegen = 1uM, NADRegen = 1uM;

// Test L to glucose conversion
protein GlucoseTransport(G --> glucose, kcat=1e9, KM=1);

// Initial conditions for transporter test
G = 0.5 mM;
GlucoseTransport = 0.5uM;

// Temporary Simulation Control Variables:
//ATP[10:10.01] = 10 mM;
SimSteps = 3000, SimRes = 100;

//@```
