// Donghoon M Lee
// EFs: elongation factors

protein EF-Tu // Binds GTP; bring Aminoacyl-tRNA to A-site of ribosome
{
    reaction TernaryComplexFormation(self~GTP + AA-tRNA --> self~GTP~AA-tRNA);
}

protein EF-Ts // Generates EF-Tu
{
    reaction TsToGTPSwap(EF-Tu~self + GTP --> EF-Tu~GTP + self);
    reaction GDPToTsSwap(EF-Tu~GDP + self --> EF-Tu~self + GDP);
}

protein EF-G // Helps in translocation of ribosome
{
    reaction GTPLoading(self + GTP --> self~GTP);
    reaction GDPtoGTPExchange(self~GDP + GTP --> self~GTP + GDP);
}

EF-Tu = 5nM;
EF-Ts = 5nM;
EF-G = 5nM;
