// Ribosomes

import InitiationFactors;
import tRNAs;

protein IF1 = InitiationFactors.IF1;
protein IF2 = InitiationFactors.IF2;
protein IF3 = InitiationFactors.IF3;

trna tRNA_initiator_Met;

protein 30S; // update to complex (many subunits)
protein 50S; // update to complex (many subunits)

complex 30SPreinitiationComplex(30S + IF1 + IF2 + GTP + IF3);
complex 30SInitiationComplex(30SPreinitiationComplex + tRNA_initiator_Met + mrna); // mrna needs to be defined

complex 70SPreinitiationComplex(30SInitiationComplex + 50S)
{
    reaction R(self.GTP --> self.GDP + self.Pi); // GTPhydrolysis
}

complex 70SInitiationComplex(70SPreinitiationComplex - IF1 - IF2 - GDP - Pi);

polymerase 70SElongationComplex(peptide_{n} + aa --> peptide_{n+1} + H2O, rate=20 aa/s, template=mrna)
{
    complex 70SInitiationComplex + any(tRNAs);

    domain ASite
    {
        bind aminoacy-tRNAs;
    }

    domain PSite
    {
        bind peptidyl-tRNA;
    }

    domain ESite
    {
        bind tRNA;
    }
}
