// Translation termination

import RNAPolymerase
// import TerminationFactors as RFs

// protein RF1 = RFs.RF1;
// protein RF2 = RFs.RF2;
// protein RF3 = RFs.RF3;

complex 70S_EC = Ribosomes.70SElongationComplex;

group<rna> StopCodons(UAA, UAG, UGA);


pathway TranslationTermination
{
    if (70S_EC.ASite.read() == any(StopCodons))
    {
        70S_EC.dissociate(StopCodon);
        // add: hydrolysis of the ester bond of the peptidyl-tRNA
        // 70S_EC.dissociate(RF1, RF2); // assisted by RF3

        70S_EC.decomplex();
    }
}
