// Translation termination

import Ribosome;
import TerminationFactor;

protein RF1 = TerminationFactor.RF1;
protein RF2 = TerminationFactor.RF2;
protein RF3 = TerminationFactor.RF3;

complex 70S_EC = Ribosome.70SElongationComplex;

pathway TranslationTermination
{
    if (70S_EC.ASite.read() == stopcodon)
    {
        70S_EC.dissociate(stopcodon);
        // add: hydrolysis of the ester bond of the peptidyl-tRNA
        // 70S_EC.dissociate(RF1, RF2); // assisted by RF3

        70S_EC.decomplex();
    }
}
