// Donghoon M. Lee, Austin Marckx, and Daehwan Kim
// 2022-09-16
// Version: 0.2
// Translation: 


// New Syntax
// _: position
// @: location
// |: binding

from tRNA import tRNA

pathway Translation
{
    // Step 1: Ribosomal complex attaching to mRNA:
    reaction initiation(30S + 70S + GTP + mRNA --> Ribosome|nascentPolypeptide@mRNA_{0} + GDP)

    // Step 2: utilize charged tRNA to build nascent polypeptide

    // Limitation: nascent Polypeptide is unavailable for binding until termination
    reaction elongation(Ribosome|nascentPolypeptide@mRNA_{i} + ctRNA --> Ribosome|nascentPolypeptide@mRNA_{i+3} + tRNA) 

    // Step 3: Termination
    reaction termination(Ribosome|nascentPolypeptide@mRNA_{terminator} --> 30S + 70S + mRNA + <proteinID>)
}

