// Donghoon M. Lee
// tRNA charging

global_import tRNA;

pathway tRNACharging
{
    // Aminoacid-tRNALigase
    protein AlaS(L-alanine + tRNA(Ala) + ATP --> L-alanyl-tRNA(Ala) + PPi + AMP);
    protein ArgS(L-arginine + tRNA(Arg) + ATP --> L-arginyl-tRNA(Arg) + PPi + AMP);    
    protein AsnS(L-asparagine + tRNA(Asn) + ATP --> L-asparaginyl-tRNA(Asn) + PPi + AMP);
    protein AspS(L-aspartate + tRNA(Asp) + ATP --> L-aspartyl-tRNA(Asp) + PPi + AMP);
    protein CysS(L-cysteine + tRNA(Cys) + ATP --> L-cysteinyl-tRNA(Cys) + PPi + AMP);
    protein GlnS(L-glutamine + tRNA(Gln) + ATP --> L-glutaminyl-tRNA(Gln) + PPi + AMP);
    protein GltX(L-glutamate + tRNA(Glu) + ATP --> L-glutamyl-tRNA(Glu) + PPi + AMP);
    protein GlyS(L-glycine + tRNA(Gly) + ATP --> L-glycyl-tRNA(Gly) + PPi + AMP);
    protein GlyQ(L-glycine + tRNA(Gly) + ATP --> L-glycyl-tRNA(Gly) + PPi + AMP);
    protein HisS(L-histidine + tRNA(His) + ATP --> L-histidyl-tRNA(His) + PPi + AMP);
    protein IleS(L-isoleucine + tRNA(Ile) + ATP --> L-isoleucyl-tRNA(Ile) + PPi + AMP);
    protein LeuS(L-leucine + tRNA(Leu) + ATP --> L-leucyl-tRNA(Leu) + PPi + AMP);
    protein LysS(L-lysine + tRNA(Lys) + ATP --> L-lysyl-tRNA(Lys) + PPi + AMP);
    protein LysU(L-lysine + tRNA(Lys) + ATP --> L-lysyl-tRNA(Lys) + PPi + AMP);
    protein MetG(L-methionine + tRNA(initiator Met) + ATP --> L-methionyl-tRNA(initiator Met) + PPi + AMP);
    protein MetG(L-methionine + tRNA(elongator Met) + ATP --> L-methionyl-tRNA(elongator Met) + PPi + AMP);
    protein PheS(L-phenylalanine + tRNA(Phe) + ATP --> L-phenylalanyl-tRNA(Phe) + PPi + AMP);
    protein PheT(L-phenylalanine + tRNA(Phe) + ATP --> L-phenylalanyl-tRNA(Phe) + PPi + AMP);
    protein ProS(L-proline + tRNA(Pro) + ATP --> L-prolyl-tRNA(Pro) + PPi + AMP);
    protein SerS(L-serine + tRNA(Ser) + ATP --> L-serine-tRNA(Ser) + PPi + AMP);
    protein ThrS(L-threonine + tRNA(Thr) + ATP --> L-threonyl-tRNA(Thr) + PPi + AMP);
    protein TrpS(L-tryptophan + tRNA(Trp) + ATP --> L-tryptophanyl-tRNA(Trp) + PPi + AMP);
    protein TyrS(L-tyrosine + tRNA(Tyr) + ATP --> L-tyrosyl-tRNA(Tyr) + PPi + AMP);
    protein ValS(L-valine + tRNA(Val) + ATP --> L-valyl-tRNA(Val) + PPi + AMP);
}
