// Donghoon M. Lee
// tRNA charging

global_import tRNA;

pathway tRNACharging
{
    // Aminoacid-tRNALigase
    protein AlaS(L-alanine + tRNA_Ala + ATP --> L-alanyl-tRNA_Ala + PPi + AMP);
    protein ArgS(L-arginine + tRNA_Arg + ATP --> L-arginyl-tRNA_Arg + PPi + AMP);    
    protein AsnS(L-asparagine + tRNA_Asn + ATP --> L-asparaginyl-tRNA_Asn + PPi + AMP);
    protein AspS(L-aspartate + tRNA_Asp + ATP --> L-aspartyl-tRNA_Asp + PPi + AMP);
    protein CysS(L-cysteine + tRNA_Cys + ATP --> L-cysteinyl-tRNA_Cys + PPi + AMP);
    protein GlnS(L-glutamine + tRNA_Gln + ATP --> L-glutaminyl-tRNA_Gln + PPi + AMP);
    protein GltX(L-glutamate + tRNA_Glu + ATP --> L-glutamyl-tRNA_Glu + PPi + AMP);
    protein GlyS(L-glycine + tRNA_Gly + ATP --> L-glycyl-tRNA_Gly + PPi + AMP);
    protein GlyQ(L-glycine + tRNA_Gly + ATP --> L-glycyl-tRNA_Gly + PPi + AMP);
    protein HisS(L-histidine + tRNA_His + ATP --> L-histidyl-tRNA_His + PPi + AMP);
    protein IleS(L-isoleucine + tRNA_Ile + ATP --> L-isoleucyl-tRNA_Ile + PPi + AMP);
    protein LeuS(L-leucine + tRNA_Leu + ATP --> L-leucyl-tRNA_Leu + PPi + AMP);
    protein LysS(L-lysine + tRNA_Lys + ATP --> L-lysyl-tRNA_Lys + PPi + AMP);
    protein LysU(L-lysine + tRNA_Lys + ATP --> L-lysyl-tRNA_Lys + PPi + AMP);
    protein MetG(L-methionine + tRNA_initiator Met + ATP --> L-methionyl-tRNA_initiator Met + PPi + AMP);
    protein MetG(L-methionine + tRNA_elongator Met + ATP --> L-methionyl-tRNA_elongator Met + PPi + AMP);
    protein PheS(L-phenylalanine + tRNA_Phe + ATP --> L-phenylalanyl-tRNA_Phe + PPi + AMP);
    protein PheT(L-phenylalanine + tRNA_Phe + ATP --> L-phenylalanyl-tRNA_Phe + PPi + AMP);
    protein ProS(L-proline + tRNA_Pro + ATP --> L-prolyl-tRNA_Pro + PPi + AMP);
    protein SerS(L-serine + tRNA_Ser + ATP --> L-serine-tRNA_Ser + PPi + AMP);
    protein ThrS(L-threonine + tRNA_Thr + ATP --> L-threonyl-tRNA_Thr + PPi + AMP);
    protein TrpS(L-tryptophan + tRNA_Trp + ATP --> L-tryptophanyl-tRNA_Trp + PPi + AMP);
    protein TyrS(L-tyrosine + tRNA_Tyr + ATP --> L-tyrosyl-tRNA_Tyr + PPi + AMP);
    protein ValS(L-valine + tRNA_Val + ATP --> L-valyl-tRNA_Val + PPi + AMP);
}
