// Donghoon M. Lee, Austin Marckx, and Daehwan Kim
// DNAMethylation

pathway DNAMethylation 
{
    // DNA methylase
    molecule SAM = S-adenosylmethionine;
    molecule SAH = S-adenosylhomocysteine;

    protein Dam(GATC + SAM --> GATC{2}~CH3 + SAH, k=1e5); // @ N6 position; ~1 site per 256 bp in DNA of random sequence (GC=AT)
    protein Dcm(CCWGG + SAM --> CCWGG{2}~CH3 + SAH, k=1e5); // @ C5 position; ~1 site per 512 bp in DNA of random sequence (GC=AT)
    protein EcoKI // ~1 site per 8 kb in DNA of random sequence (GC=AT)
    {
        reaction Methylation1(AACNNNNNNG TGC + 2 SAM --> AACNNNNNNG TGC{1}~CH3 + AACNNNNNNG TGC{2}~CH3 + 2 SAH, k=1e5);
        reaction Methylation2(GCACNNNNNN GTT + SAM --> GCACNNNNNN GTT{3}~CH3 + SAH, k=1e5);
    }

    // TODO: SAH to SAM conversion pathway (transsulfuration, aminopropylation)
    // arbitrary reaction to restore SAM
    reaction ReplenishSAM(SAH + H2O + ATP --> SAM + ADP + Pi + H+, k=1e3);
}

reference NEB_Methylases
{
    title = "Dam and Dcm Methylases of E. coli"
    url = "https://www.neb.com/tools-and-resources/usage-guidelines/dam-and-dcm-methylases-of-e-coli"
}
