// Donghoon M. Lee, Austin Marckx, and Daehwan Kim
// Replication machineries

dna DMS = ds(GATC);
dna mDMS = dsDNA(GATC{2}~CH3);
dna hmDMS = dsDNA(GATC{2}~CH3/rc(GATC));

dna OriginOfReplication
{
    motif DnaABox = 10; // GmATC, where mA indicates methylated Adenine by Dam
    motif SegSite = 10;
    gene dnaA = 1;
    // also contains a copy of dnaA gene
}

protein DnaA // Origin-binding protein; Binds origin of replication to open double helix
{
    reaction ATPBinding(self + ATP --> self~ATP, Kd=1e-10);
    reaction DnaABoxBinding(self~ATP + DnaABox.mDMS --> self~ATP~DnaABox, Kd=1e-10);
    reaction DnaABoxBinding(self~ATP + DnaABox.hmDMS --> self~ATP~DnaABox, Kd=1e-2);
    reaction dsDNAUnwinding(self~ATP~dsDNA --> self~ATP~ssDNA + ssDNA, r=10)
}

protein SeqA
{
    reaction DnaABoxBinding(self + DnaABox.hmDMS --> self~DnaABox, Kd=1e-2);
    reaction dnaAPromoterBinding(self + dnaA.promoter --> self~dnaA.promoter, Kd=1e-10);
}

protein DnaB // Helicase; Unwinds double helix at replication fork
{
    reaction DNABinding(self + dsDNA --> self~dsDNA);
    reaction HelicaseActivity
    {
        float R = 10.0;
        reaction dsDNAUnwinding(self~dsDNA --> self~ssDNA + ssDNA, r=R); // rate of initiation?
        reaction DNATranslocation(self~dsDNA{n} --> self~dsDNA{n+1}, r=R);
    }
}

protein DnaG // primase
{
    reaction DNABinding(self + ssDNA --> self~ssDNAm Kd=1e-10);
    reaction OligoSynthesis(self~ssDNA.N_{10} + c(dNTP) --> self~ssDNA~c(RNA.N_{10}), r=20);
}

complex Primosome(DnaB + DnaG, Kd=1-10);

protein DnaC // Helicase loader; Loads helicase at origin
{
    reaction DNABinding(self + DnaA~ATP~ssDNA --> DnaA~ATP~ssDNA~self, Kd=1e-10);
    reaction PrimosomeRecruitment(DnaA~ssDNA~self + Primosome --> DnaA + ssDNA~self~Primosome, Kd=1-9);
}

protein gyrAB(sc(DNA) --> DNA); // DNA gyrase that resolves supercoiled DNA


complex Replisome
{
    reaction Complexation(gyrAB + 2 DNAPIII + ssDNA~DnaA~self~Primosome, Kd=1-10);
    reaction Recruitment
}


protein DnaE; // Polymerase subunit; Strand elongation
protein DnaQ; // Proofreading subunit; Proofreading


protein DnaN; // Sliding clamp; Holds Pol III on DNA

protein LigA(N^N --> NN); // DNA ligase

protein Ssb
{
    DNA_binding ssDNA; // prevents hybridization of ssDNAs
}

complex DNAPIII(DnaE + DnaQ) // currently subunits are not assigned function for low resolution description
{
    reaction R1(dna_{n} + nt --> dna_{n+1} + ppi, rate=1000 nt/s, template=chromosome); // Main polymerizing enzyme
    // update with more double stranded dna context later (dna_{n}/dna + nt --> dna_{n+1}/dna + ppi)
}

protein PolA // DNA polymerase I
{
    reaction R1(rna/dna --> -/dna); // 5'-end exonuclease; Excises RNA primer
    reaction R2(dna_{n} + nt --> dna_{n+1} + ppi, rate=1000 nt/s, template=chromosome); // polymerization; fills in gaps
}





// for termination
dna TerminusOfReplication // terminus of replication
{
    motif Ter = 10;
}

protein Tus
{
    DNA_binding TerminusOfReplication.Ter;
}

reference BrockBiologyOfMicroorganisms_Table4_2
{
    title = "Brock Biology of Microorganisms";
    edition = 15;
    publisher = "Pearson";
    authors = "Madigan", "Bender", "Buckley", "Sattley", "Stahl";

    table T4_2
    {
        title = "Major enzymes that participate in DNA replication in Bacteria";
        page = 147;
    }
}

// Enzyme                          Encoding genes      Function
// DNA gyrase                      gyrAB               Replaces supercoils ahead of replisome
// Origin-binding protein          dnaA                Binds origin of replication to open double helix
// Helicase loader                 dnaC                Loads helicase at origin
// Helicase                        dnaB                Unwinds double helix at replication fork
// Single-strand binding protein   ssb                 Prevents single strands from annealing
// Primase                         dnaG                Primes new strands of DNA
// DNA polymerase III                                  Main polymerizing enzyme
// Sliding clamp                   dnaN                Holds Pol III on DNA
// Clamp loader                    holA-E              Loads Pol III onto sliding clamp
// Dimerization subunit (Tau)      dnaX                Holds together the two core enzymes for the leading and lagging strands
// Polymerase subunit              dnaE                Strand elongation
// Proofreading subunit            dnaQ                Proofreading
// DNA polymerase I                polA                Excises RNA primer and fills in gaps 
// DNA ligase                      ligA, ligB          Seals nicks in DNA
// Tus protein                     tus                 Binds terminus and blocks progress of the replication fork
// Topoisomerase IV                parCE               Unlinking of interlocked circles

reference Xu_Dixon_2018
{
    title = "Bacterial replisomes";
    doi = "10.1016/j.sbi.2018.09.006";
    // doi_url = "https://doi.org/10.1016/j.sbi.2018.09.006";
}