// BSD 3-Clause License
// © 2022, The University of Texas Southwestern Medical Center. All rights reserved.
// Donghoon M. Lee and Daehwan Kim

// Bacterial Chemotaxis

import BacterialChemotaxis;
import FlagellarRotation;

CheA = BacterialChemotaxis.CheA;
CheAm = BacterialChemotaxis.CheAm;
CheR = BacterialChemotaxis.CheR;
CheB = BacterialChemotaxis.CheB;
CheBP = BacterialChemotaxis.CheBP;

pathway CellMotility
{
    pathway BacterialChemotaxis
    {
        membrane CellMembrane
        {
            CheA_Methylation = CheR.CheA_Methylation;
            CheAL_Methylation = CheR.CheAL_Methylation;
            CheAm_Demethylation = CheBP.CheAm_Demethylation;
            CheAmL_Demethylation = CheBP.CheAmL_Demethylation;
            CheB_Phosphorylation = CheAm.CheB_Phosphorylation;
            CheAm_LigandBinding = BacterialChemotaxis.CheAm_LigandBinding;
            CheA_LigandBinding = BacterialChemotaxis.CheA_LigandBinding;

            float thAm = 0.982;
            bool bRun = Am < thAm;

            Motility = FlagellarRotation.FlagellarRotation(CellMembrane, bRun);

            CheA = 500nM;
        }
        cytosol Cytosol
        {
            CheR = 5nM;
            CheB = 0.1nM;
        }
    }
}

reference Porter_2011
{
    title = "Signal processing in complex chemotaxis pathways";
    doi = "https://doi.org/10.1038/nrmicro2505";
}
