// Donghoon M. Lee, Austin Marckx, and Daehwan Kim
// Glucose Transport

// Transport 6-carbon sugar into cell.
reaction GlucoseTransporter(glucose --> G6P, k=1)
mathfunc
{
    float cgt = 0.5uM;
    G6P' = glucose/G6P * cgt;
    glucose' = 0 - G6P';
};

glucose = 0.15 M;
G6P = 8.8e-3 M;
ATP = 9.6e-3 M;
ADP = 5.6e-4 M;


// pathway GlucoseTransporter(glucose --> G6P)
// func
// {
//     float cgt = 0.5uM;
//     G6P' = glucose/G6P * cgt;
//     glucose' = - G6P';
// }
// {

// }
