// BSD 3-Clause License
// © 2022, The University of Texas Southwestern Medical Center. All rights reserved.
// Donghoon M. Lee and Daehwan Kim

// Glucose Transport

// temporary code with limited parsing
reaction GlucoseTransport(glucose{out} --> G6P{in})
specification
{
    float cgt = 0.5 M;
    G6P' = glucose/G6P * cgt;
    glucose' = - G6P';
}

G6P = 8.8e-3 M;
ATP = 9.6e-3 M;
ADP = 5.6e-4 M;
