// Glycolysis
// input: G6P
// output: 2 pyruvate + 2 NADH + 2 ATP

// citation Marckx2022("reference");
// document;

pathway GlucoseMetabolism
{
  protein Glycolysis(glucose + 2 Pi + 2 ADP + 2 NAD --> 2 pyruvate + 2 ATP + 2 NADH + 2 H + 2 H2O, kcat=9.51e28, KM=1e29 uM);
  protein pyruvateDehydrogenase(pyruvate + NAD + CoA --> acetylCoA + CO2 + NADH + H, kcat=6.8e19, KM=1e20 uM);
  protein TCACycle(acetylCoA + 3 NAD + FAD + ADP + Pi + 2 H2O --> 2 CO2 + 3 NADH + FADH2 + ATP + 2 H + CoA, kcat=5.19e19, KM=1e20 uM);
}

// Set constant and variable concentrations:
//glucose[:] = 0.5 mM;
H2O[:] = 8 M, O2[:] = 5 mM, CO2[:] = 0 mM;
Pi = 5 mM, ADP = 0.17 mM, FAD = 2 mM, NAD = 2.6 mM, NADH = 83 uM, ATP = 5.5 mM, CoA = 2.0 mM;

// Initial conditions for enzymes
Glycolysis = 0.32uM, pyruvateDehydrogenase = 0.48uM, TCACycle = 0.8uM;
