//pathway Glycolysis(glucose --> 2 pyruvate + 2 NADH + 2 ATP)

pathway Glycolysis
{
    protein HexoKinase(glucose + ATP --> F6P + ADP, k = 4e3);
    
    protein PhosphoFructoKinase
    {
        // Set up regulatory domain
        domain Regulatory
        {
            reaction ToActive(self.Regulatory + ADP --> self.Regulatory~ADP);
            reaction ToInhib(self.Regulatory + PEP --> self.Regulatory~PEP);
        }
        // Alias active, inhibited, neutral PFK
        PFKa = self.Regulatory~ADP;
        PFKn = self.Regulatory;
        PFKi = self.Regulatory~PEP;

        reaction Active(PFKa + F6P + ATP --> F16BP + ADP, kcat = 1.7e4, KM = 0.21uM);
        reaction Neutral(PFKn + F6P + ATP --> F16BP + ADP, kcat = 1.7e4, KM = 3.1e7uM);
        reaction Inhibited(PFKi + F6P + ATP --> F16BP + ADP, kcat = 1.7e4, KM = 3.1e7uM);
    }
    // Fake Protein, add NADH in such that low and med have same outputs.
    virtual protein PepSynthase(F16BP --> 2 PEP + 2 NADH + 2 ATP, k = 1e6);

    protein PyruvateKinase(PEP + ADP --> ATP, kcat = 170, KM = 700uM);
}
