// Ingalls 2013 Mathematical Modelling in Systems Biology
//
// Product Inhibition
// Network  4.1,   p.78
// Model   4.1,    p.77
// Figure  4.2,    p.78

// standard reactions
reaction R1(In --> S1, k=20);
reaction R2(In --> S2, k=5);
reaction R3(S1 --> Out, k=5);
reaction R4(S2 --> Out, k=5);
reaction R5(S1 --> S2, k=2);

// regulatory reaction
reaction R6(S2 --| R1, Ki=0.5, n=4);

In[:] = 1, Out[:] = 0;

