// Donghoon M. Lee, Austin Marckx, and Daehwan Kim
// Limit Cycle Oscillations

reference Ingalls_2013
{
    title = "Mathematical Modelling in Systems Biology";
    page = 93;
    figure = 4.14;      // Network
    equation = 4.10;    // Equation
    page += 94;
    figure += 4.15.A;   // Plot
}

reaction R1(In --> S1, k=8);
reaction R2(S1 --> S2, k=1);
reaction R3(S2 --> Out, k=5);
reaction R4(S2 --> R2, Ka=1, n=2);

// initial quantity
In[:]=1, Out[:]=0;
S1[0]=1.5, S2[0]=1;







