// Ingalls 2013 Mathematical Modelling in Systems Biology
//
// MichaelisMenten
// Network	3.2,	p.49
// Figure	3.3,	p.50


// k1 = 30;
// krev1 = 1;
// k2 = 10;
// KM = (krev1 + k2) / k1;

// standard reaction
reaction R1(E + S --> ES, k=30M, krev=1M);
reaction R2(ES --> E + P, k=10M);

// initial quantity
E=1M, S=5M;

// enzymatic reaction
protein e(s --> p, kcat=10, KM=0.3666667M);

// initial quantity
e=1M, s=5M;

SimSteps = 500, SimRes = 500;
