name: lcc
channels:
  - defaults
dependencies:
  - python=3.8
  - pip
  - numpy
  - cmake
  - grpcio-tools
  - pip:
      - tensorflow
      - matplotlib
      - plot
      - asyncio
      - grpcio
      - protobuf
      - pygame
