// Donghoon M. Lee, Austin Marckx, and Daehwan Kim
// Divisome proteins

// cytosolic proteins
protein FtsZ // Tubulin-like principal regulator of septal PG synthesis
{
    domain GB; // Guanine nucleotide binding
    reaction GDPBinding(self.GB + GDP --> self.GB~GDP, Kd=1e-10);
    reaction NucExchange(self.GB~GDP + GTP --> self.GB~GTP + GDP, Kd=1e-10);
    
    // DK: the following line could be redundant with the general one, self.GB~GTP_{n} + self.GB~GTP_{m} --> self.GB~GTP_{n+m}
    reaction Nucleation(2 self.GB~GTP --> (self.GB~GTP)_{2}, Kd=1e-3);
    reaction Polymerization((self.GB~GTP)_{n} + (self.GB~GTP)_{m} --> (self.GB~GTP)_{n+m}, Kd=1e-6); // two different molecules

    // reaction Hydrolysis(self.GB~GTP_{n} + n H2O --> self.GB~GTP_{n-1} + 1 GDP + Pi, Kd=1e-4); // reduced model for bending and removal
    // reaction Dissociation(self.GB~GTP_{n} --> n self.GB~GTP, Kd=1e-7);
}

// membrane proteins
protein FtsA // Primary membrane tether of FtsZ; recruitment of other division proteins
// & ZipA for FtsZ membrane recruitment
{
    reaction FtsZMembraneRecruitment(self + (FtsZ~GTP)_{10}{in} --> self~((FtsZ~GTP)_{10}), k=1e5, krev=1e2); // for simplicity and due to limited syntax
}

protein ZipA; // Alternate membrane tether of FtsZ; enhances recruitment of other division proteins; preseptal PG synthesis
// & ZipC, ZipD for Z ring assembly

complex ZRing
{
    reaction Assembly(FtsA~((FtsZ~GTP)_{10}) + ZipA, k=1e5, krev=1e2); 
}

protein FtsK; // Recruitment of other division proteins; chromosome segregation; PG synthesis
// & FtsE/X, FtsQ/L/B, FtsW/I, PBP1b, FtsN for divisome formation and activation
// protein AmiB, AmiC, NlpD, Tol-Pal for divisome action to separate daughter cells

complex Divisome
{
    reaction Complexation(ZRing + FtsK, k=1e5, krev=1e2);
    reaction Oligomerization(self_{n} + self --> self_{n+1}, k=1e5, krev=1e2);
    reaction Splitting(self_{n+m} --> self_{n} + self_{m}, Kd=1e-2);
    reaction Constriction(self_{n} + 10 H2O --> self_{n-1} + self.GB~GDP + 10 Pi{in}, Kd=1e-7); // reduced model for bending and removal. Consider treadmilling mechanism in the updates.
    reaction Dissociation(self.GB~GDP --> (FtsZ~GDP)_{10}{in} + FtsA + ZipA + FtsK, Kd=1e-2);
}    

reference LevinJanakiraman_2021
{
    title = "Localization, Assembly, and Activation of the Escherichia coli Cell Division Machinery";
    doi = "https://doi.org/10.1128/ecosalplus.ESP-0022-2021";
}

reference Nguyen_2021
{
    title = "Simulations of Proposed Mechanisms of FtsZ-Driven Cell Constriction";
    doi = "https://doi.org/10.1128/JB.00576-20";
}

// references for FtsZ quantity
reference Kumar_2017
{
    title = "Z-ring Structure and Constriction Dynamics in E. coli";
    doi = "https://doi.org/10.3389/fmicb.2017.01670";
    // there are ~300 FtsZ proteins in low growth rate E. coli cells (generation time > 100 min) (Link et al., 1997) and 
    // 3,000–15,000 in high growth rate E. coli (generation time ≃ 20 min) (Lu et al., 1998; Rueda et al., 2003). 
}

reference Link_1997
{
    title = "Comparing the predicted and observed properties of proteins encoded in the genome of Escherichia coli K-12";
    doi = "https://doi.org/10.1002/elps.1150180807";
}

reference Lu_1998
{
    title = "FtsZ from Escherichia coli, Azotobacter vinelandii, and Thermotoga maritima–quantitation, GTP hydrolysis, and assembly.";
    doi = "https://doi.org/10.1002/(SICI)1097-0169(1998)40:1<71::AID-CM7>3.0.CO;2-I";
}

reference Rueda_2003
{
    title = "Concentration and assembly of the division ring proteins FtsZ, FtsA, and ZipA during the Escherichia coli cell cycle";
    doi = "https://doi.org/10.1128/JB.185.11.3344-3351.2003";
}
