// BSD 3-Clause License
// © 2022, The University of Texas Southwestern Medical Center. All rights reserved.
// Donghoon M. Lee and Daehwan Kim

// Divisome proteins

// protein FtsZ; // Tubulin-like protein
// {
//     // Option 1. No domain declaration. Note: Linear polymerization and interaction domain info are indistinguishable from aggregation
//     reaction Polymerization(self_{n} + self_{m} --> self_{n+m}, Kd=1e-2); // Nucleation and polymerization
//     // reaction InterPolymerBinding(self_{n}{n} + self_{m}{1} --> self_{n}{n}~self_{m}{1}, Kd=1e-1);
//     // reaction Treadmilling(self_{n}{n}~self_{m}{1} --> self_{n}{n-1}~self_{m}{2}, r=1);
//     // Alternatives: 
//     // reaction InterPolymerBinding(self_{n} + self_{m} --> self_{n}.self{n}~self_{m}.self{1}, Kd=1e-1);
//     // reaction Treadmilling(self_{n}.self{n}~self_{m}.self{1} --> self_{n}.self{n-1}~self_{m}.self{2}, r=1);

//     // Option 2. three domains declaration
//     // domain P1, P2; // Polymerization domains (cis interaction for polymerization)
//     // domain TD; // Treadmilling domain (trans polymer interaction for treadmilling), avoiding T to distinguish from Threonine access
//     reaction Polymerization(self_{n} + self_{m} --> self_{n}{n}.P1~self_{m}{1}.P2); // Nucleation and polymerization
//     // reaction InterPolymerBinding(self_{n}{n}.TD + self_{m}{1}.TD --> self_{n}{n}.TD~self_{m}{1}.TD, Kd=1e-1);
//     // reaction Treadmilling(self_{n}{n}.TD~self_{m}{1}.TD --> self_{n}{n-1}.TD~self_{m}{2}.TD, r=1);
// }

// protein FtsA; // Primary membrane tether of FtsZ;
complex Divisome
{
    protein FtsZ, FtsA; // FtsZ is a cytosolic protein, whereas FtsA is an integral membrane protein
    reaction DivisomeFormation(FtsA~(FtsZ_{n}) + FtsZ{in} --> FtsA~(FtsZ_{n+1})); // FtsZ monomer recruitment and polymerization (n can be 0, as well)
    Divisome = FtsA~(FtsZ_{n});
    k_function
    {

    }
    krev_function
    {

    }
    reaction InterFtsZPolymerBinding(FtsA~(FtsZ_{n}){n} + FtsA~(FtsZ_{m}){1} --> (FtsA~(FtsZ_{n}){n})~(FtsA~(FtsZ_{m}){1}), r=1);
    reaction FtsZ_Treadmilling((FtsA~(FtsZ_{n}){n})~(FtsA~(FtsZ_{m}){1}) --> (FtsA~(FtsZ_{n}){n-1})~(FtsA~(FtsZ_{m}){2}), r=1);
}

reference LevinJanakiraman_2021
{
    title = "Localization, Assembly, and Activation of the Escherichia coli Cell Division Machinery";
    doi = "https://doi.org/10.1128/ecosalplus.ESP-0022-2021";
}

reference Nguyen_2021
{
    title = "Simulations of Proposed Mechanisms of FtsZ-Driven Cell Constriction";
    doi = "https://doi.org/10.1128/JB.00576-20";
}

// references for FtsZ quantity
reference Kumar_2017
{
    title = "Z-ring Structure and Constriction Dynamics in E. coli";
    doi = "https://doi.org/10.3389/fmicb.2017.01670";
    // there are ~300 FtsZ proteins in low growth rate E. coli cells (generation time > 100 min) (Link et al., 1997) and 
    // 3,000–15,000 in high growth rate E. coli (generation time ≃ 20 min) (Lu et al., 1998; Rueda et al., 2003). 
}

reference Link_1997
{
    title = "Comparing the predicted and observed properties of proteins encoded in the genome of Escherichia coli K-12";
    doi = "https://doi.org/10.1002/elps.1150180807";
}

reference Lu_1998
{
    title = "FtsZ from Escherichia coli, Azotobacter vinelandii, and Thermotoga maritima–quantitation, GTP hydrolysis, and assembly.";
    doi = "https://doi.org/10.1002/(SICI)1097-0169(1998)40:1<71::AID-CM7>3.0.CO;2-I";
}

reference Rueda_2003
{
    title = "Concentration and assembly of the division ring proteins FtsZ, FtsA, and ZipA during the Escherichia coli cell cycle";
    doi = "https://doi.org/10.1128/JB.185.11.3344-3351.2003";
}
