// Donghoon M. Lee, Austin Marckx, and Daehwan Kim
// DNA Segregation

import ParABS; // temporary system, not native to E coli.
import SMC;

ParA = ParABS.ParA;
ParB = ParABS.ParB;

MukBEF = SMC.MukBEF;

pathway DNASegregation
{
    membrane CellMembrane
    {
        reaction ParARecruitment = ParA.MembraneRecruitment;
        reaction ParBSRecruitment = ParA.ParBSRecruitment;
        reaction ParBSRelease = ParX.MembraneRecruitment;
        reaction ParAInactivation = ParX.ATPaseActivity;
        reaction MembraneDetatchment = ParX.MembraneDetatchment;

        cytosol Cytosol
        {
            reaction ParBDimerization = ParB.Dimerization;
            reaction ChromosomeBinding = ParB.DNABinding;
            reaction ParXDimerization = ParX.Dimerization;

            pathway ChromosomeCondensation
            {
                reaction MukBEFAssembly = MukBEF.Complexation;
                reaction MukBEFDimerization = MukBEF.Dimerization;
                reaction Condensation = MukBEF.Condensation;
            }
        }
    }
}
