// Donghoon M. Lee, Austin Marckx, and Daehwan Kim
// MinCDE system

import Divisome;

FtsZ = Divisome.FtsZ;
FtsA = Divisome.FtsA;

// all cytosolic proteins
protein MinC; // Binds to the core region of FtsZ to inhibit FtsZ Polymerization
{
    reaction Dimerization(2 self --> self~self, Kd = 1e9);
    reaction FtsZSequestration(MinC_Dimer + FtsZ~GDP --> MinC_Dimer~FtsZ~GDP, k = 1e9);
}

protein MinD // Walker-type ATPase, tethers MinC to membrane via MinE
{
    reaction MembraneRecruitment_1(2 self~ADP{in} + 2 ATP{in} --> (self~ATP)~(self~ATP) + 2 ADP{in}, k = 1e9); // via ATP-dependent dimerization
    MinD_Dimer = (self~ATP)~(self~ATP);
    reaction MembraneRecruitment_2(MinD_Dimer + 2 MinD~ADP{in} + ATP{in} --> 2 MinD_Dimer + 2 ADP{in}, k = 1e9); // via positive feedback
    MinC_Dimer = MinC~MinC;
    reaction MinCRecruitment(MinD_Dimer + MinC_Dimer{in} --> MinD_Dimer~MinC_Dimer, k = 1e9);
    FtsZInhibition(MinD_Dimer~MinC_Dimer + FtsA~(FtsZ~GTP_{10}) --> MinD_Dimer~MinC_Dimer + FtsA{in} + 10 FtsZ~GTP{in}, k = 1e9); // hypothetical model for simplicity
}

protein MinE; // Binds to MinD and stimulates ATPase activity of MinD, leading to the release of MinD from the membrane
{
    reaction Dimerization(2 self --> self~self, Kd = 1e-9);
    MinE_Dimer = self~self;
    reaction MembraneRecruitment(MinE~MinE{in} + MinD_Dimer~MinC_Dimer --> MinD_Dimer~MinE_Dimer + MinC_Dimer{in}, k = 1e9); // stronger than MinD.MembraneRecruitment_2
    reaction ATPaseActivity(MinD_Dimer~MinE_Dimer + 2 H2O{in} --> MinE_Dimer~(MinD~GDP)~(MinD~GDP) + 2 Pi{in}, k=1e9);
    reaction MembraneDetatchment(MinE_Dimer~(MinD~GDP)~(MinD~GDP) --> MinE_Dimer{in} + (MinD~GDP)~(MinD~GDP){in}, k=1e9);
    // reaction Reassociation(MinE_Dimer~(MinD~GDP)~(MinD~GDP) + MinD_Dimer --> MinE_Dimer~MinD_Dimer + 2 (MinD~GDP){in}, k=1e9);
}

protein SlmA; // Effector of nucleoid occlusion

MinD = 10nM;
MinC = 10nM;
MinE = 5nM;
