// BSD 3-Clause License
// © 2022, The University of Texas Southwestern Medical Center. All rights reserved.
// Donghoon M. Lee and Daehwan Kim

// MinCDE system - positioning the FtsZ ring precisely at the midcell
pathway MinCDE
{
    // protein MinD, MinE, MinC;
    membrane Membrane;

    reaction MinD_MembraneRecruitment(Membrane~MinD_{n} + MinD {in} --> Membrane~MinD_{n+1}) // n may be 0
    k_function
    {
        // Spherical coordinate system - https://en.wikipedia.org/wiki/Spherical_coordinate_system
        MaxMembraneEffect = (0.5 * pi) ** 2;
        NewAngle = Membrane.phi;
        if (NewAngle >= pi)
        {
            NewAngle = NewAngle - pi;
        }
        MembraneEffect = (NewAngle - 0.5 * pi) ** 2 / MaxMembraneEffect * 1.1;
        AggregationEffect = log(max(2, Membrane~MinD_{n}), 2);
        return MembraneEffect * AggregationEffect;
    }
    krev_function
    {
        return k_function() * (Membrane~MinE_{n} / max(1, Membrane~MinD_{m})) * normal(1.5, 0.2);
    }

    reaction MinE_MembraneRecruitment(Membrane~MinD_{n}~MinE_{m} + MinE{in} --> Membrane~MinD_{n}~MinE_{m+1})
    k_function
    {
        return MinD_MembraneRecruitment.k_function() * 0.2;
    }
    krev_function
    {
        return max(0, Membrane~MinE_{n} - Membrane~MinD_{m});
    }

    reaction MinC_MembraneRecruitment(MinD_Dimer + MinC_Dimer{in} --> MinD_Dimer~MinC_Dimer, k = 1e9)
    k_function
    {
        return MinD_MembraneRecruitment.k_function() * 0.2;
    }
    krev_function
    {
        return max(0, Membrane~MinC_{n} - Membrane~MinD_{m});
    }
}

MinD = 4928; // # of proteins, Ramm_2019 Table 1
MinC = 163; // # of proteins, Ramm_2019 Table 1
MinE = 4004; // # of proteins, Ramm_2019 Table 1

reference Ramm_2019
{
    title = "The E. coli MinCDE system in the regulation of protein patterns and gradients";
    doi = "https://doi.org/10.1007/s00018-019-03218-x";
}
