// Donghoon M. Lee, Austin Marckx, and Daehwan Kim
// ParABS - distributing DNA along with the cell (temporarily used in E. coli)

DNA parS;

// all cytosolic proteins
protein ParB // similar to MinC
{
    reaction Dimerization(2 self --> self~self, Kd = 1e9);
    reaction DNABinding(self~self + parS --> (self~self)~parS, k = 1e9);
}
ParBS = (ParB~ParB)~parS;

protein ParA // similar to MinD
{
    reaction MembraneRecruitment(2 self~ADP{in} + 2 ATP{in} --> (self~ATP)~(self~ATP) + 2 ADP{in}, k = 1e9); // via ATP-dependent dimerization
    ParA_Dimer = (self~ATP)~(self~ATP);
    reaction ParBSRecruitment(ParA_Dimer + ParBS{in} --> ParA_Dimer~ParBS, k = 1e9);
}

virtual protein ParX // imaginery protein to build an artificial chromosome segregation system, which act like MinE in MinCDE system.
{
    reaction Dimerization(2 self --> self~self, Kd = 1e-9);
    ParX_Dimer = self~self;
    reaction MembraneRecruitment(ParX_Dimer{in} + ParA_Dimer~ParBS --> ParA_Dimer~ParX_Dimer + ParBS{in}, k = 1e9);
    reaction ATPaseActivity(ParA_Dimer~ParX_Dimer + 2 H2O{in} --> ParX_Dimer~(ParA~GDP)~(ParA~GDP) + 2 Pi{in}, k=1e9);
    reaction MembraneDetatchment(ParX_Dimer~(ParA~GDP)~(ParA~GDP) --> ParX_Dimer{in} + (ParA~GDP)~(ParA~GDP){in}, k=1e9);
}

reference Merino-Salomon_2021
{
    title = "Self-organized protein patterns: The MinCDE and ParABS systems";
    doi = "https://doi.org/10.1016/j.ceb.2021.07.001";
}
