// BSD 3-Clause License
// © 2022, The University of Texas Southwestern Medical Center. All rights reserved.
// Donghoon M. Lee and Daehwan Kim

// Septum Formation

import Divisome;
import MinCDE;

ZRing = Divisome.ZRing;

pathway SeptumFormation
{
    membrane CellMembrane
    {
        pathway MidlineDetermination
        {
            MinD_MembraneRecruitment = MinCDE.MinCDE.MinD_MembraneRecruitment;
            MinE_MembraneRecruitment = MinCDE.MinCDE.MinE_MembraneRecruitment;
            MinC_MembraneRecruitment = MinCDE.MinCDE.MinC_MembraneRecruitment;
        }

        pathway Cytokinesis
        {
            FtsZ_MembraneRecruitment = ZRing.FtsZ_MembraneRecruitment;
            FtsZ_Crosslinking = ZRing.FtsZ_Crosslinking;
            FtsZ_Treadmilling = ZRing.FtsZ_Treadmilling;
        }

        // CP: removed units after function call
        // DL: removed spatial coordinates and assume uniform distribution
        FtsA = 792; // Schmidt_2016 from LB dataset

        cytosol Cytosol
        {
            MinC = 163;
            MinD = 4928;
            MinE = 4004;

            FtsZ = 7898; // Schmidt_2016 from LB dataset
        }
    }
}

reference CorbinErickson_2020
{
    title = "A Unified Model for Treadmilling and Nucleation of Single-Stranded FtsZ Protofilaments";
    doi = "https://doi.org/10.1016/j.bpj.2020.05.041";
}

reference Ramm_2019
{
    title = "The E. coli MinCDE system in the regulation of protein patterns and gradients";
    doi = "https://doi.org/10.1007/s00018-019-03218-x";
}

reference Schmidt_2016
{
    title = "The quantitative and condition-dependent Escherichia coli proteome";
    doi = "https://doi.org/10.1038/nbt.3418";
}
