// Donghoon M. Lee, Austin Marckx, and Daehwan Kim
// SMC (Structural Maintenance of the Chromosome)

// tripartite MukBEF complex for E coli
protein MukB, MukE, MukF;

complex MukBEF // condenses chromosomes with long-ranged (scales > 280 kb) intra-chromosomal contacts
{
    MukBEF_Dimer = self~self;
    reaction Complexation(2 MukB + 2 MukE + MukF + ssDNA, Kd = 1e-9);
    reaction Dimerization(2 self + ssDNA--> MukBEF_Dimer~ssDNA, Kd = 1e-9);
    reaction Condensation(2 MukBEF_Dimer~ssDNA --> (MukBEF_Dimer~ssDNA)~(MukBEF_Dimer~ssDNA), Kd = 1e-9);
    // MukBEF_DimerOfDimer = (MukBEF_Dimer~ssDNA)~(MukBEF_Dimer~ssDNA);
}

// DK
#if 0
complex MukBEF // condenses chromosomes with long-ranged (scales > 280 kb) intra-chromosomal contacts
{
    reaction Complexation(2 MukB + 2 MukE + MukF, Kd = 1e-9);
    reaction Dimerization(MukBEF + MukBEF --> MukBEF_Dimer, Kd = 1e-9);
    reaction Condensation(MukBEF_Dimer + dsDNA{n} + dsDNA{n+80, n+120} --> (MukBEF~dsDNA{n})~(MukBEF~dsDNA{n+80, n+120}), Kd = 1e-9);
}
#endif

// antagonist system to MukBEF to prevent chromosome rotation during the division
// DNA matS;
// protein MatP; // binds matS sites to prevent MukBEF-induced long-range contacts in the ter macrodomain.

// XerCD/dif system
// DNA dif;
// protein XerC, XerD; // bind at the dif site in the terminus domain and catalyze the resolution of chromosome dimers that arise as a result of replication

reference Gogou_2021
{
    title = "Mechanisms for Chromosome Segregation in Bacteria";
    doi = "https://doi.org/10.3389/fmicb.2021.685687";
}

reference MakelaSherratt_2020
{
    title = "Organization of the Escherichia coli Chromosome by a MukBEF Axial Core";
    doi = "https://doi.org/10.1016/j.molcel.2020.02.003";
}    
