// Donghoon M. Lee, Austin Marckx, and Daehwan Kim
// SMC (Structural Maintenance of the Chromosome)

// tripartite MukBEF complex for E coli
protein MukB, MukE, MukF;

complex MukBEF // condenses chromosomes with long-ranged (scales > 280 kb) intra-chromosomal contacts
{
    reaction Complexation(2 MukB + 2 MukE + MukF, Kd=1e-9);
}

// antagonist system to MukBEF
DNA matS;

protein MatP; // binds matS sites to prevent MukBEF-induced long-range contacts in the ter macrodomain.

// XerCD/dif system
// DNA dif;
// protein XerC, XerD; // bind at the dif site in the terminus domain and catalyze the resolution of chromosome dimers that arise as a result of replication

reference Gogou_2021
{
    title = "Mechanisms for Chromosome Segregation in Bacteria";
    doi = "https://doi.org/10.3389/fmicb.2021.685687";
}
