// BSD 3-Clause License
// © 2022, The University of Texas Southwestern Medical Center. All rights reserved.
// Donghoon M. Lee, Chanhee Park, and Daehwan Kim

// Translation

import Ribosome;

R30S = Ribosome.R30S;
R50S = Ribosome.R50S;
R70S = Ribosome.R70S;
AA_tRNASynthetase = Ribosome.AA_tRNASynthetase;

pathway Translation
{
    reaction Initiation
    {
        InitialtRNAloading = R30S.InitialtRNAloading;
        Complexation = R70S.Complexation;
    }
    
    reaction Elongation
    {
        CodonRecognition = R70S.CodonRecognition;
        PeptidylTransfer = R70S.Elongation.PeptidylTransfer;
        RNATranslocation = R70S.Elongation.RNATranslocation;
    }

    // Step 3. Termination: see Ribosome
    reaction Termination 
    {
        StopCodonRecognition = R70S.StopCodonRecognition;
        PeptideRelease = R70S.PeptideRelease;
        Dissociation = R70S.Dissociation;
    }

    tRNACharging = AA_tRNASynthetase.tRNACharging;

    R30S = 50000;
    R50S = 50000;

    IF = 10000;
    EF_Tu = 443852; // tufA
    EF_G = 86623; // fusA
    RF = 2000; 
    RRF = 8329; // frr

    tRNA = 375000;
    AA[:] = 90mM;
    AA_tRNASynthetase = 87102;
}

reference ThomasSteitz_2008
{
    title = "A structural understanding of the dynamic ribosome machine";
    doi = "https://doi.org/10.1038/nrm2352";
}

reference Rodnina_2018
{
    title = "Translation in Prokaryotes";
    doi = "https://doi.org/10.1101/cshperspect.a032664";
}
