// Misincorporation of Adenine
reaction R2(dsDNA.C/8-oxoG --> dsDNA.A/8-oxoG, k=0.005);

// 8-oxoGTP level control
protein MutT(8-oxoGTP --> 8-oxoGMP, kcat=1, KM=1e-5);

// DNA damage response
pathway BaseExcisionRepair
{
    // adenine excision
    protein MutY(dsDNA.A/8-oxoG --> dsDNA.-/8-oxoG, kcat=1, KM=1e-8);

    // Incision case 1: Apurinic/apyrimidinic (AP) endonucleases (XthA or members of the End family)


    // Incision case 1: β-elimination (by Nth)
    // protein

    // Incision case 2: δ-elimination (by MutM or Nei)

    // DNA BaseExcision by DNA glycosylase (MutM, Nth, Nei, MutY, Ung, AlkA, Mug, and Tag)
    protein MutM(dsDNA.C/8-oxoG --> dsDNA.C/-, kcat=35, KM=1e-14); // assumption: resulting in 5′-phosphate and 3′-hydroxyl groups

    // Incision case 3: DNA backbone cleavage by Apurinic/apyrimidinic (AP) endonucleases (XthA or members of the End family)
    // protein


    // gap filling
    protein PolA(dsDNA.N/- --> dsDNA.N/P, kcat=1e2, KM=1e-30); // P was used to indicate com(p)lementary base

    // ligation
    protein LigA(DNA.N^N --> NN, kcat=1e2, KM=1e-10);

}

8-oxoGTP = 0.5mM, MutT = 1nM;
MutY = 1nM, MutM = 1nM, PolA = 1nM, LigA = 1nM;