// BSD 3-Clause License
// © 2023, The University of Texas Southwestern Medical Center. All rights reserved.
// Donghoon M. Lee and Daehwan Kim

// Glucose Transport

from MetaboliteConcentrations import *;

import MetaboliteConcentrations;

float D_gt = 1e3;
float Init_G6P = MetaboliteConcentrations.G6P;

reaction GlucoseTransport(glucose{out} + ATP -> G6P{in} + ADP)
specification
{
    G6P' = glucose * (Init_G6P - G6P) * D_gt;
}
