// alpha-D-galactofuranoseABCTranporter
// target: alpha-D-galactofuranose
// periplasm --> cytosol
// DB: EcoCyc
// - TRANS-RXN0-492
// EC Number: 7.5.2.9
// Link: https://biocyc.org/ECOLI/NEW-IMAGE?object=TRANS-RXN0-492
// Notes: 
// yjfF, ytfR, ytfT, ytfQ
Transporter alpha-D-galactofuranoseABCTranporter(alpha-D-galactofuranose_periplasm + ATP + H2O --> alpha-D-galactofuranose_cytosol + ADP + P + H);
