// N-acetyl-D-glucosaminePTSTransporter
// target: N-acetyl-D-glucosamine
// periplasm --> cytosol
// DB: EcoCyc
// - TRANS-RXN-157
// EC Number: 2.7.1.199
// Link: https://biocyc.org/ECOLI/NEW-IMAGE?object=TRANS-RXN-157
// Notes: 
// Mannose Specific PTS enzymeII: manZ, manY, manX
Transporter N-acetyl-D-glucosaminePTSTransporter(N-acetyl-D-glucosamine_periplasm + HPr-P --> N-acetyl-D-glucosamine-6P_cytosol + HPr);
