// Donghoon M. Lee, Austin Marckx, and Daehwan Kim
// E. coli Code v0.1

medium MinimalMedium
{
    glucose = 10nM;
}

medium RichMedium
{
    AA aa = {Gly, Ser, Ala, ...};
    aa = 10nM;

    glucose = 10nM;
}

organism Ecoli
{
    membrane CellMembrane
    {
        cytosol Cytosol
        {

        }
    }
}

reference RaetzDowhan_1990
{
    title = "Biosynthesis and function of phospholipids in Escherichia coli";
    doi = "https://doi.org/10.1016/S0021-9258(19)40001-X";
}
