// BSD 3-Clause License
// © 2022, The University of Texas Southwestern Medical Center. All rights reserved.
// Donghoon M. Lee and Daehwan Kim

// E. coli Code v0.1

import CellDivision.BinaryFission;
import CellMotility.CellMotility;
import GeneticInfoProcessing.Degradation.ProteinDegradation;
import GeneticInfoProcessing.Degradation.RNADegradation;
import GeneticInfoProcessing.Transcription.Transcription;
import GeneticInfoProcessing.Translation.Translation;
import Metabolism.GlucoseMetabolism;

organism Ecoli
{
    CellDivision = CellDivision.BinaryFission.BinaryFission;
    BacterialChemotaxis = CellMotility.CellMotility.CellMotility;
    ProteinDegradation = GeneticInfoProcessing.Degradation.ProteinDegradation.ProteinDegradation;
    RNADegradation = GeneticInfoProcessing.Degradation.RNADegradation.RNADegradation;
    Transcription = GeneticInfoProcessing.Transcription.Transcription.Transcription;
    Translation = GeneticInfoProcessing.Translation.Translation.Translation;
    GlucoseMetabolism = Metabolism.GlucoseMetabolism.GlucoseMetabolism;

    membrane CellMembrane
    {
        cytosol Cytosol
        {

        }
    }
}

glucose L(800, 500, 0) = 100nmol;
Ecoli(500, 600, 0) = 1;

reference RaetzDowhan_1990
{
    title = "Biosynthesis and function of phospholipids in Escherichia coli";
    doi = "https://doi.org/10.1016/S0021-9258(19)40001-X";
}

reference Valgepea_2013
{
    title = "Escherichia coli achieves faster growth by increasing catalytic and translation rates of proteins";
    doi = "DOI	https://doi.org/10.1039/C3MB70119K";
    table = "S1";
}
