// BSD 3-Clause License
// © 2022, The University of Texas Southwestern Medical Center. All rights reserved.
// Donghoon M. Lee and Daehwan Kim

// Energy Consumption

reaction EnergyConsumption(ATP + NAD -> ADP + NADH) // for cell division
specification
{
    float ce = 4.35E-3M;
    ADP' = ce;
    ATP' = - ADP';
    float cb = 0.7725; // NAD rebalancing factor
    NAD' = ATP' * cb; 
    NADH' = - NAD';
}
