// BSD 3-Clause License
// © 2022, The University of Texas Southwestern Medical Center. All rights reserved.
// Donghoon M. Lee and Daehwan Kim

// Glycolysis

reaction Glycolysis(G6P + 2 ADP + 2 NAD --> 2 pyruvate + 2 NADH + 2 ATP)
specification
{
    float cg = 0.019 M;
    ATP'  = (ADP / ATP) * cg;
    ADP'  = - ATP';
    NADH' = ATP';
    NAD' = - NADH';
    G6P'  = ATP' / 2;
    pyruvate' = G6P' * 2;
}
