// BSD 3-Clause License
// © 2022, The University of Texas Southwestern Medical Center. All rights reserved.
// Donghoon M. Lee and Daehwan Kim

// Oxidative Phosphorylation

reaction OxidativePhosphorylation(NADH + FADH2 + 4 ADP --> NAD + FAD + 4 ATP)
specification
{
    float c_co = 5 M;
    float co = FADH2 * c_co;
    ATP'  = co;
    ADP'  = - ATP';
    NADH' = - ATP' / 4;
    FADH2' = - ATP' / 4;
    NAD' = - NADH';
    FAD' = - FADH2';
}
