// BSD 3-Clause License
// © 2023, The University of Texas Southwestern Medical Center. All rights reserved.
// Donghoon M. Lee and Daehwan Kim

// Purine Synthesis

pathway PurineSynthesis
{
    // TODO: convert to biochem
    reaction IMPSynthesis(PRPP -> IMP)
    specification
    {
        float ci = 0.019M;
        IMP'  = (1 / IMP) * ci;
    }

    reaction PurineSynthesis(PRPP -> IMP)
    specification
    {
        float ci = 0.019M;
        IMP'  = (1 / IMP) * ci;
    }

    // TODO: GMP, GDP, GTP, dGTP
    // TODO: AMP, ADP, ATP, dATP

}
