petridish P
{
  ecoli E
  {
    pathway Chemotaxis
    {
      protein R
      {
        reaction R1(A --> Am, kcat=1, KM=1e-10nM);
        reaction R2(AL --> AmL, kcat=1, kM=1e-10nM);
      }

      protein BP
      {
        reaction R1(Am --> A, kcat=200, KM=1nM);
        reaction R2(AmL --> AL, kcat=1, KM=1nM);
      }

      protein Am
      {
        reaction R(B --> BP, k=0.05e9, krev=0.005);
      }

      reaction R1(Am + L --> AmL, k=1e9, krev=1);
      reaction R2(A + L --> AL, k=1e9, krev=1);

    }
  
    flagellum F(Am, 0.982 nM);

    R = 5nM, B = 0.1nM, A = 500nM;

    pathway QuorumSensing
    {
//      protein AmL
//      {
//        reaction R2(pc_qL --> qL, kcat=1, KM=1nM);
//      }

      protein qR
      {
        reaction R1(qA --> qAm, kcat=1, KM=1e-10nM);
        reaction R2(qAL --> qAmL, kcat=1, kM=1e-10nM);
      }

      protein qBP
      {
        reaction R1(qAm --> qA, kcat=200, KM=1nM);
        reaction R2(qAmL --> qAL, kcat=1, KM=1nM);
      }

      protein qAm
      {
        reaction R(qB --> qBP, k=0.05e9, krev=0.005);
      }

      reaction R3(qAm + qL --> qAmL, k=1e9, krev=1);
      reaction R4(qA + qL --> qAL, k=1e9, krev=1);

    }

    flagellum F(qAm, 0.982 nM);

    qR = 5nM, qB = 0.1nM, qA = 500nM;
    pc_qL[:] = 500 nM;

  }

  // spatially distributed entities on petridish

  E(350, 300, 0) = 1;
  E(750, 450, 0) = 41;

  glucose L;
  L(800, 600, 0) = 5 nmol;

  Autoinducer qL;
  qL = 0.1 nmol;

  F = 3;

}

// at ~ 410 and 500, top left ecoli starts to move to glucose
