// BSD 3-Clause License
// (c) 2023, The University of Texas Southwestern Medical Center. All rights reserved.
// Donghoon M. Lee and Daehwan Kim

// E. coli Code v0.2

import CellMotility.CellMotility;

organism Ecoli
{
    membrane CellMembrane
    {
        cytosol Cytosol
        {
            CellMotility = CellMotility.CellMotility.CellMotility;
        }
    }
}

L(0, 0, 0) = 20nmol;
Ecoli(0.267, 0.1, 0) = 1;

