petridish P
{
  ecoli E
  {
    pathway Chemotaxis
    {
      protein R
      {
        reaction R1(A --> Am, kcat=1, KM=1e-10nM);
        reaction R2(AL --> AmL, kcat=1, kM=1e-10nM);
      }

      protein BP
      {
        reaction R1(Am --> A, kcat=200, KM=1nM);
        reaction R2(AmL --> AL, kcat=1, KM=1nM);
      }

      protein Am
      {
        reaction R(B --> BP, k=0.05e9, krev=0.005);
      }

      reaction R1(Am + L --> AmL, k=1e9, krev=1);
      reaction R2(A + L --> AL, k=1e9, krev=1);

    }

    R = 5nM, B = 0.1nM, A = 500nM;
  }

  // spatially distributed entities on petridish
  E(200, 200, 0) = 1;
  E(700, 400, 0) = 1;
  
  glucose L;
  L(800, 600, 0) = 9 nmol;
}

