petridish P
{
  ecoli E
  {
    pathway Chemotaxis
    {
      protein AmL(pc_qL --> qL, kcat=1, KM=1nM);

      protein R
      {
        reaction R1(A --> Am, kcat=1, KM=1e-10nM);
        reaction R2(AL --> AmL, kcat=1, kM=1e-10nM);
      }

      protein BP
      {
        reaction R1(Am --> A, kcat=200, KM=1nM);
        reaction R2(AmL --> AL, kcat=1, KM=1nM);
      }

      protein Am
      {
        reaction R(B --> BP, k=0.05e9, krev=0.005);
      }

      reaction R1(Am + L --> AmL, k=1e9, krev=1);
      reaction R2(A + L --> AL, k=1e9, krev=1);

//      transporter TL(L, ki=1e9);
    }

    R = 5nM, B = 0.1nM, A = 500nM;
    TL = 100nM;

    pathway QuorumSensing
    {

      protein qR
      {
        reaction R1(qA --> qAm, kcat=1, KM=1e-10nM);
        reaction R2(qAL --> qAmL, kcat=1, kM=1e-10nM);
      }

      protein qBP
      {
        reaction R1(qAm --> qA, kcat=200, KM=1nM);
        reaction R2(qAmL --> qAL, kcat=1, KM=1nM);
      }

      protein qAm
      {
        reaction R(qB --> qBP, k=0.05e9, krev=0.005);
      }

      reaction R2(qAm + qL --> qAmL, k=1e9, krev=1);
      reaction R3(qA + qL --> qAL, k=1e9, krev=1);

//      transporter TqL(qL, ko=1e5);
    }

    qR = 5nM, qB = 0.1nM, qA = 500nM;
 
    pc_qL[:] = 0.0001nM;
    TqL = 0.001nM;
  }

  // spatially distributed entities on petridish
  for (i = 0; i < 10; i = i + 1)
  {
    E(i * 100, 700, 0) = 1;
  }

  for (i = 0; i < 10; i = i + 1)
  {
    E(i * 100, 100, 0) = 1;
  }

  glucose L;
  L(800, 600, 0) = 5nmol;

  Autoinducer qL;
//  qL(0, 0, 0) = 0;

}
