// Ingalls 2013 Mathematical Modelling in Systems Biology
//
// Product Inhibition
// Network  4.1,   p.78
// Model   4.1,    p.77
// Figure  4.2,    p.78

// standard reactions
reaction R1(S1In --> S1, k=20);
reaction R2(S2In --> S2, k=5);
reaction R3(S1 --> S1Out, k=5);
reaction R4(S2 --> S2Out, k=5);
reaction R5(S1 --> S2, k=2);

// regulatory reaction
reaction R6(S2 --| R1, Ki=1, n=4);

S1In[:] = 1;
S2In[:] = 1;
S1Out[:] = 0;
S2Out[:] = 0;

