// Ingalls 2013 Mathematical Modelling in Systems Biology
//
// Stability
// Network  4.6,   p.82
// Model   4.2,    p.82
// Figure  4.7,    p.83

protein E1(S1In --> S1, k=20, Inhibitor=S2, Ki=1, Mode=Allosteric, n=4, E1=1, S=1, S1In=1, Fixed=S1In);
protein E2(S2In --> S2, k=20, Inhibitor=S1, Ki=1, Mode=Allosteric, n=1, E2=1, S=3, S2In=1, Fixed=S2In);
protein E3(S1 --> S1Out, k=5, E3=1);
protein E4(S2 --> S2Out, k=5, E4=1);



