// Ingalls 2013 Mathematical Modelling in Systems Biology
//
// Network  6.13,   p.163
// Model   6.12,    p.162
// Figure  6.14,    p.164

// N_SimSteps = 100000, SimStepTimeResolution = 100
// Note: ligand induction time interval change similar to the python model

// Protein amounts imported from Bitbol and Wingreen, 2015 Biophysical Journal. Fundamental Constraints on the Abundances of Chemotaxis Proteins.
// CheA = 2.97 uM, CheY = 9.73 uM, CheZ = 3.80 uM, CheB = 0.28 uM, CheR = 0.17 uM, FliM = 1.43 uM, where 16% of FliM that are free are discounted.


    protein BP
    {
      reaction R1(Am --> A, kcat=200, KM=1M);
      reaction R2(AmL --> AL, kcat=1, KM=1M);
    }

    protein R
    {
      reaction R1(A --> Am, kcat=1, KM=0.001M); // seems correct
      reaction R2(AL --> AmL, kcat=1, KM=0.001M); // seems correct
    }

    reaction R1(Am + L_NoPlot --> AmL, k=6e23, krev= 6e23);
    reaction R2(A + L_NoPlot --> AL, k=6e23, krev= 6e23);
    reaction R3(B + Am --> BP, k=5e22, krev= 5e21);

    A = 500 M, R = 5 M, B = 0.1 M;
    //L_NoPlot[0:100]= 1.244e25, L_NoPlot[100:300]= 2.488e25;
    L_NoPlot[0:100]= 20e6 M, L_NoPlot[100:300]=40e6 M;
    //L[300:500]=80 M;

    SimSteps = 2000, SimRes = 100;
