// Ingalls 2013 Mathematical Modelling in Systems Biology
//
// Product Inhibition
// Network  4.1,   p.78
// Model   4.1,    p.77
// Figure  4.2,    p.78

protein E1(S1In --> S1, k=20, Inhibitor=S2, Mode=Allosteric, Ki=1, n=4);
protein E2(S2In --> S2, k=5);
protein E3(S1 --> S1Out, k=5);
protein E4(S2 --> S2Out, k=5);
protein E5(S1 --> S2, k=2);

E1[0]=1; S1In[:]=1;
E2[0]=1; S2In[:]=1;
E3[0]=1; S1Out[:]=0;
E4[0]=1; S2Out[:]=0;
E5[0]=1;
