// Ingalls 2013 Mathematical Modelling in Systems Biology
//
// Stability
// Network  4.6,   p.82
// Model   4.2,    p.82
// Figure  4.7,    p.83

// standard reactions
reaction R1(S1In --> S1, k=20);
reaction R2(S2In --> S2, k=20);
reaction R3(S1 --> S1Out, k=5);
reaction R4(S2 --> S2Out, k=5);

// regulatory reactions
reaction R5(S2 --| R1, Ki=1, n=4);
reaction R6(S1 --| R2, Ki=1, n=1);

// initial quantity
S1[0] = 1;
S1In[:] = 1;
S2[0] = 3;
S2In[:] = 1;
S1Out[:] = 0;
S2Out[:] = 0;