// Ingalls 2013 Mathematical Modelling in Systems Biology
//
// Network  6.13,   p.163
// Model   6.12,    p.162
// Figure  6.14,    p.164

// N_SimSteps = 100000, SimStepTimeResolution = 100
// Note: ligand induction time interval change similar to the python model

    protein BP
    {
      reaction R1(Am --> A, kcat=200, KM=1);
      reaction R2(AmL --> AL, kcat=1, KM=1);
    };

    protein R
    {
      // original code according to the book, requiring explicit saturation conditioned simulation code
      // reaction R1(A --> Am, k=1);
      // reaction R2(AL --> AmL, k=1);

      // updated code to use regular simulation code
      reaction R1(A --> Am, kcat=1, KM=1.0e-10);
      reaction R2(AL --> AmL, kcat=1, KM=1.0e-10);
    };

    reaction R1(Am + L --> AmL, k=1, krev=1);
    reaction R2(A + L --> AL, k=1, krev=1);
    reaction R3(B + Am --> BP, k=0.05, krev=0.005);

    A[0] = 500, R[0] = 5, B[0] = 0.1;
    L[0:100]=20, L[100:300]=40, L[300:500]=80;
