// Ingalls 2013 Mathematical Modelling in Systems Biology
//
// Network  6.13,   p.163
// Model   6.12,    p.162
// Figure  6.14,    p.164

// N_SimSteps = 30000, SimStepTimeResolution = 100
// Note: ligand induction time interval change similar to the python model

// Protein amounts imported from Bitbol and Wingreen, 2015 Biophysical Journal. Fundamental Constraints on the Abundances of Chemotaxis Proteins.
// CheA = 2.97 uM, CheY = 9.73 uM, CheZ = 3.80 uM, CheB = 0.28 uM, CheR = 0.17 uM, FliM = 1.43 uM, where 16% of FliM that are free are discounted.


petridish P
{
  ecoli E
  {
    protein R
    {
      reaction R1(A --> Am, kcat=1, KM=1e-10nM);
      reaction R2(AL --> AmL, kcat=1, kM=1e-10nM);
    }

    protein BP
    {
      reaction R1(Am --> A, kcat=200, KM=1nM);
      reaction R2(AmL --> AL, kcat=1, KM=1nM);
    }

    protein Am
    {
      reaction R(B --> BP, k=0.05e9, krev=0.005);
    }

    reaction R1(Am + L --> AmL, k=1e9, krev=1);
    reaction R2(A + L --> AL, k=1e9, krev=1);

    R = 5nM, B = 0.1nM, A = 500nM;
  }

  for (i = 0; i < 10; i = i + 1)
  {
    E(rand(400, 600), rand(400, 600), 0) = 1;
  }

  glucose L;
  L(800, 500, 0) = 100nmol;
}



