// BSD 3-Clause License
// (c) 2023, The University of Texas Southwestern Medical Center. All rights reserved.
// Donghoon M. Lee, Chanhee Park, and Daehwan Kim

// Bacterial Chemotaxis

import BacterialChemotaxis;
import FlagellarRotation;

CheA = BacterialChemotaxis.CheA;
CheAm = BacterialChemotaxis.CheAm;
CheR = BacterialChemotaxis.CheR;
CheB = BacterialChemotaxis.CheB;
CheBP = BacterialChemotaxis.CheBP;

pathway CellMotility
{
    pathway BacterialChemotaxis
    {
        // SE: this doesn't work with the current lcc as, for example, CheA_Methylation is treated as a pure reaction without a protein involve, which is not the case.
        /*
        CheA_Methylation = BacterialChemotaxis.CheR.CheA_Methylation;
        CheAL_Methylation = BacterialChemotaxis.CheR.CheAL_Methylation;
        CheAm_Demethylation = BacterialChemotaxis.CheBP.CheAm_Demethylation;
        CheAmL_Demethylation = BacterialChemotaxis.CheBP.CheAmL_Demethylation;
        CheB_Phosphorylation = BacterialChemotaxis.CheAm.CheB_Phosphorylation;
        CheAm_LigandBinding = BacterialChemotaxis.CheAm_LigandBinding;
        CheA_LigandBinding = BacterialChemotaxis.CheA_LigandBinding;
        */

        Che_Methylation = BacterialChemotaxis.CheR;
        Che_Demethylation = BacterialChemotaxis.CheBP;
        Che_Phosphorylation = BacterialChemotaxis.CheAm;
        CheAm_LigandBinding = BacterialChemotaxis.CheAm_LigandBinding;
        CheA_LigandBinding = BacterialChemotaxis.CheA_LigandBinding;
    }
     
    float threshold_CheAm = 0.982;
    bool bRun = CheAm < threshold_CheAm;

    Motility = FlagellarRotation.FlagellarRotation(CellMembrane, bRun);

    // CheA = 500nM, CheR = 5nM, CheB = 0.1nM;
    CheA = 33.265358nM, CheAL = 447.503671nM, CheAm =  0.981218nM, CheAmL = 18.249753nM;
    CheR = 5nM, CheB = 0nM, CheBP = 0.1nM;
}

reference Porter_2011
{
    title = "Signal processing in complex chemotaxis pathways";
    doi = "https://doi.org/10.1038/nrmicro2505";
}
