// BSD 3-Clause License
// © 2022, The University of Texas Southwestern Medical Center. All rights reserved.
// Donghoon M. Lee and Daehwan Kim

// Glucose Metabolism

import GlucoseTransport;
import Glycolysis;
import PyruvateOxidation;
import CitrateCycle;
import OxidativePhosphorylation;
import EnergyConsumption;

pathway GlucoseMetabolism
{
    membrane CellMembrane
    {
        GlucoseTransporter = GlucoseTransport.GlucoseTransport;

        cytosol Cytosol
        {
            Glycolysis = Glycolysis.Glycolysis;
            PyruvateOxidation = PyruvateOxidation.PyruvateOxidation;
            CitrateCycle = CitrateCycle.CitrateCycle;
            OxidativePhosphorylation = OxidativePhosphorylation.OxidativePhosphorylation;
            EnergyConsumption = EnergyConsumption.EnergyConsumption;

            G6P[:] = 8.8mM;
            ATP = 9.6mM;
            ADP = 0.56mM;
            NADH = 83.2nM;
            NAD = 2.6mM;
            pyruvate = 0.39mM;
            CoA_SH[:] = 1.4mM;
            acetyl_CoA = 0.61mM;
            FADH2 = 0.5mM;
            FAD = 0.17mM;
            Malate = 1.7mM;
        }
    }
}

reference KimGadd_2008   // ATP requirements for polymer synthesis in E coli.
{
    title = "Bacterial Physiology and Metabolism.";
    page = "191";
    table = "6.10";
    page += "192";
    table += "6.11";
} 

// Table 6.10. ATP requirement for polymer synthesis by Escherichia coli using glucose–mineral salts medium
// Polymer  ATP required for the synthesis of polymer to make up one gram dry wt cell material (mmol/g dry wt)
//
// Polysaccharide   2.1
//
// Protein
// Glucose to amino acids   1.4
// Polymerization (translation) 19.1
//
// Lipid    0.1
//
// RNA
// Glucose to ribonucleotides   3.5
// Polymerization (transcription)   0.9
//
// DNA
// Glucose to deoxyribonucleotides  0.9
// Polymerization   0.2
//
// Transport    5.2
// 
// RNA turnover 1.4
//
// Overall  34.8
//
