// BSD 3-Clause License
// © 2022, The University of Texas Southwestern Medical Center. All rights reserved.
// Donghoon M. Lee and Daehwan Kim

// Bacterial Chemotaxis

reference Ingalls_2013
{
    title = "Mathematical Modelling in Systems Biology";
    page = 161;
    figure = 6.10;  // Diagram
    page += 162;
    figure += 6.11; // Diagram
    equation = 6.0; // Network (6.0 for unannotated equation in chapter 6)
    page += 163;
    figure += 6.12; // Network
    figure += 6.13; // Network
    page += 164;
    figure += 6.14; // Plot
}

// N_SimSteps = 100000, SimStepTimeResolution = 100

protein R
{
  reaction R1(A --> Am, kcat=1, KM=1e-10nM);
  reaction R2(AL --> AmL, kcat=1, kM=1e-10nM);
}

protein BP
{
  reaction R1(Am --> A, kcat=200, KM=1nM);
  reaction R2(AmL --> AL, kcat=1, KM=1nM);
}

protein Am
{
  reaction R(B --> BP, k=0.05e9, krev=0.005);
}

reaction R1(Am + L --> AmL, k=1e9, krev=1);
reaction R2(A + L --> AL, k=1e9, krev=1);

R = 5nM, B = 0.1nM, A = 500nM;
L[0:100] = 20nM, L[100:200] = 40nM, L[200:300] = 80nM;

// temporary simulation parameters
SimSteps = 30000, SimRes = 100;
