// BSD 3-Clause License
// © 2022, The University of Texas Southwestern Medical Center. All rights reserved.
// Donghoon M. Lee and Daehwan Kim

// MichaelisMenten

reference Ingalls_2013
{
    title = "Mathematical Modelling in Systems Biology";
    page = 49;
    equation = 3.2;     // Network
    page += 50;
    figure = 3.3;       // Plot
    equation += 3.3;    // Equation
}

// k1 = 30;
// krev1 = 1;
// k2 = 10;
// KM = (krev1 + k2) / k1;

// standard reaction
reaction R1(E + S --> ES, k=30M, krev=1M);
reaction R2(ES --> E + P, k=10M);

// initial quantity
E = 1M, S = 5M;

// enzymatic reaction
protein e(s --> p, kcat=10, KM=0.3666667M);

// initial quantity
e = 1M, s = 5M;

// temporary simulation parameters
SimSteps = 500, SimRes = 500;
