// BSD 3-Clause License
// © 2022, The University of Texas Southwestern Medical Center. All rights reserved.
// Donghoon M. Lee and Daehwan Kim

// G-protein Signaling

reference Ingalls_2013
{
    title = "Mathematical Modelling in Systems Biology";
    page = 153;
    figure = 6.4;       // Diagram
    page += 154;
    figure += 6.5.A;    // Plot
    equation = 6.0;     // Network (6.0 for unannotated equation in chapter 6)
    // Equation is no available from the text
}

// Suggested N_SimSteps / SimStepTimeResolution : 1000

reaction R1(R + L --> RL, k=2.0e+6, krev=1e-2);
reaction R2(G + RL --> Ga + Gbg + RL, k=6.022140900000001e+18);
reaction R3(Ga --> Gd, k=0.11);
reaction R4(Gd + Gbg --> G, k=6.0221409e+23);

R = 6.6421561142815505e-21;
L[:] = 0;
L[100:700] = 1e-9;
G = 1.6605390285703877e-20;

// temporary simulation parameters
SimSteps = 10000, SimRes = 10;
