// BSD 3-Clause License
// © 2022, The University of Texas Southwestern Medical Center. All rights reserved.
// Donghoon M. Lee and Daehwan Kim

// Binary Fission

import DNAReplication.DNAReplication;
import DNASegregation;
import SeptumFormation;

pathway BinaryFission
{
    DNAReplication = DNAReplication.DNAReplication.DNAReplication;
    DNASegregation = DNASegregation.DNASegregation;
    SeptumFormation = SeptumFormation.SeptumFormation;
}

reference LevinJanakiraman_2021
{
    title = "Localization, Assembly, and Activation of the Escherichia coli Cell Division Machinery";
    doi = "https://doi.org/10.1128/ecosalplus.ESP-0022-2021";
}
