// BSD 3-Clause License
// (c) 2023, The University of Texas Southwestern Medical Center. All rights reserved.
// Donghoon M. Lee and Daehwan Kim

// Bacterial Chemotaxis

protein CheR
{
    reaction CheA_Methylation(CheA -> CheAm, kcat=1, KM=1e-10nM);
    reaction CheAL_Methylation(CheAL -> CheAmL, kcat=1, KM=1e-10nM);
}

protein CheB;
protein CheBP
{
    reaction CheAm_Demethylation(CheAm -> CheA, kcat=200, KM=1nM);
    reaction CheAmL_Demethylation(CheAmL -> CheAL, kcat=1, KM=1nM);
}

protein CheA;
protein CheAm
{
    reaction CheB_Phosphorylation(CheB -> CheBP, k=0.05e9, krev=0.005);
}

reaction CheAm_LigandBinding(CheAm + L{out} -> CheAmL, k=1e9, krev=1);
reaction CheA_LigandBinding(CheA + L{out} -> CheAL, k=1e9, krev=1);

reference BitbolWingreen_2015
{
    title = "Fundamental Constraints on the Abundances of Chemotaxis Proteins";
    doi = "https://doi.org/10.1016/j.bpj.2015.01.024";
}

reference Ingalls_2013
{
    title = "Mathematical Modelling in Systems Biology: An Introduction";
    doi = "https://www.math.uwaterloo.ca/~bingalls/MMSB/MMSB_w_solutions.pdf";
}

reference Alon_1999
{
    title = "Robustness in bacterial chemotaxis";
    doi = "https://doi.org/10.1038/16483";
}
