// BSD 3-Clause License
// © 2022, The University of Texas Southwestern Medical Center. All rights reserved.
// Donghoon M. Lee and Daehwan Kim

// Flagellar Rotation

membrane Membrane;

// CP
reaction FlagellarRotation(Membrane, bRun) // bRun is a boolean parameter
specification
{
    Ang = Membrane.phi;
    Pos = Membrane.position;

    cdist = 10nm/s; // constant for displacement
    crot = rand(0, 2 * pi); // constant for rotation

    if (bRun)
    {
        Pos' = cdist;
        Ang' = 0;
    }
    else 
    {
        Pos' = cdist / 3;
        Ang' = crot;
    }
}
