// Donghoon M. Lee, Austin Marckx, and Daehwan Kim
// Flagellar Rotation

import BacterialChemotaxis;
Am = BacterialChemotaxis.Am;

pathway FlagellarRotation(membrane, bRun) // bRun is a boolean parameter
mathfunc
{
    Ang = membrane.angle;
    Pos = membrane.position;

    cdist = 10nm/s; // constant for displacement
    crot = rand(0, 360)°; // constant for rotation

    if (bRun)
    {
        dPos/dt = cdist;
        dAng/dt = 0;
    }
    else 
    {
        dPos/dt = cdist / 3;
        dAng/dt = crot;
    }
}
