// E coli.lpp

petridish P
{
    ecoli E
    {
        pathway Replication
        {
            replication_origin origin1;
            replication_terminus terminus1;
            polymerase pol1(initiation: origin1,
                            elongation: dna_{n} + dnt -->
                                       dna_{n+1} + ppi,
                            termination: terminus1);
        }

        pol1 = 100;
        dATP = 1nM, dCTP = 1nM, dGTP = 1nM, dTTP = 1nM;

        pathway Transcription
        {
            // rnap_binding_site promoter;
            // transcription_terminator taa;
            polymerase rnap(initiation: promoter,
                            elongation: rna_{n} + nt -->
                                        rna_{n+1} + ppi,
                            termination: taa);
        }

        rnap = 300;
        ATP = 1nM, CTP = 1nM, GTP = 1nM, UTP = 1nM;

        pathway Translation
        {
            ribosome_binding_site rbs1;
            translation_terminator tt1;
            ribosome r1(initiation: rbs1,
                        elongation: peptide_{n} + aa -->
                                    peptide_{n+1} + H_{2}O,
                        termination: tt1);
        }

        r1 = 500;
        ALA = 1nM, ARG = 1nM, ASN = 1nM, ASP = 1nM, CYS = 1nM, GLT = 1nM, GLN = 1nM;
        GLY = 1nM, HIS = 1nM, ILE = 1nM, LEU = 1nM, LYS = 1nM, MET = 1nM, PHE = 1nM;
        PRO = 1nM, SER = 1nM, THR = 1nM, TRP = 1nM, TYR = 1nM, SEL = 1nM, VAL = 1nM;

    }
}