organism ecoli "E. coli K-12 MG1655";

// DNA Replication
replication_origin origin1;
replication_terminus terminus1;
polymerase pol1(initiation: origin1, 
               elongation: dna_{n} + dnt -->
                           dna_{n+1} + ppi, 
               termination: terminus1);

// RNA Transcription
rnap_binding_site promoter;
transcription_terminator taa;
polymerase rnap(initiation: promoter, 
                elongation: rna_{n} + nt -->
                            rna_{n+1} + ppi,
                termination: taa);

// Protein Translation
ribosome_binding_site rbs1;
translation_terminator tt1;
ribosome r1(initiation: rbs1,
            elongation: peptide_{n} + aa -->
                        peptide_{n+1} + H_{2}O, 
            termination: tt1);

// Tricarboxylic Acid Cycle (TCA)
protein GltA(oxaloacetate + acetyl-CoA + H2O --> citrate + CoA);
protein AcnA(citrate --> isocitrate);
protein Icd(isocitrate + NAD+ --> keto-glutarate + NADH + CO2);
protein SucA(keto-glutarate + NAD+ + CoA --> succinyl-CoA + NADH + CO2);
protein SucD(succinyl-CoA + ADP + Pi --> succinate + ATP + CoA);
protein Sdh(succinate + FAD --> fumarate + FADH2);
protein FumA(fumarate + H2O --> malate);
protein Mdh(malate + NAD+ --> oxaloacetate + NADH + H+);

pathway TCA = GltA --> AcnA --> Icd --> SucA --> SucD --> Sdh --> FumA --> Mdh;

// Carbonic Anhydrase
protein ca2(CO_{2} + H_{2}O --> OHCOO^{-} + H^{+})
{
   cofactor co1(zn^{2+});
   domain dom1(co1-his, co1-his, col1-his);
   step step1(dom1 + H_{2}O --> dom1-OH^{-} + H^{+});
   step step2(dom1-OH^{-} + CO_{2} --> dom1-OHCOO^{-});
   step step3(dom1-OHCOO^{-} --> dom1 + OHCOO^{-});
   sequence process1(step1, step2, step3);
};

// Endocytosis
// Courtesy of Xinxin Wang from UT Southwestern.
protein clathrin()
{
   PDB "1XI4";
   domain dom1();
   domain dom2();
};

process clathrin_endocytosis()
{
   step step1(clathrin.dom1 + clathrin.dom1 -->
                     clathrin.dom1-clathrin.dom1);
   step step2(clathrin.dom2 + clathrin.dom2 -->
                     clathrin.dom2-clathrin.dom2);
};
