/* Define template organism */
organism ecoli "E-coli \"K-12 MG1655\"";

/* Define experiment environment */
/* TODO */
experiment my_expr "TCA Cycle";

/* Define proteins */
// FIXME:
protein GltA(oxaloacetate + acetyl-CoA --> citrate); // GltA
protein AcnA(citrate --> isocitrate);
protein AcnB(citrate --> isocitrate);
protein Icd(isocitrate --> keto-glutarate);
protein SucA();
protein SucB();

// TCA
pathway OLD_TCA = GltA --> AcnA | AcnB --> Icd --> SucA + SucB --> SucD + SucC --> Sdh --> FUM --> Mdh --> GltA;
// New pathway format
//

pathway TCA {
	description "TCA";
	reaction_id r101013;
	reaction GltA --> AcnA | AcnB --> Icd --> SucA + SucB --> SucD + SucC --> Sdh --> FUM --> Mdh --> GltA;
};
