/* Define template organism */
organism ecoli "E-coli K-12 MG1655";

/* Define experiment environment */
/* TODO */
experiment my_expr {
	description "TCA Cycle";
	property temperature 37.0;
	property medium LB;
};

using module Transcription;
//using module Replication;

/* Define proteins */
// FIXME:
protein GltA(oxaloacetate + acetyl-CoA --> citrate); // GltA
protein AcnA(citrate --> isocitrate);
protein AcnB(citrate --> isocitrate);
protein Icd(isocitrate --> keto-glutarate);
protein SucA();
protein SucB();
protein Fume();

// TCA
pathway OLD_TCA = GltA --> AcnA | AcnB --> Icd --> SucA + SucB --> SucD + SucC --> Sdh --> Fume --> Mdh --> GltA;

// New pathway format

pathway TCA {
	description "TCA";
	reaction_id r101013;
	reaction GltA --> AcnA | AcnB --> Icd --> SucA + SucB --> SucD + SucC --> Sdh --> Fume --> Mdh --> GltA;
};
