//@# Tricarboxylic Acid Cycle (TCA) or Citric Acid Cycle (CAC)
//@
//@![TCA_Image](TCA_Image.png)
//@Reference: [Stryer Biochemistry 7ed](https://www.amazon.com/Biochemistry-Lubert-Stryer/dp/1319114679/ref=sr_1_1?keywords=Stryer+Biochemistry&qid=1636994919&s=books&sr=1-1).
//@
//@```
protein GltA(oxaloacetate + acetyl-CoA --> citrate);
protein AcnA(citrate --> isocitrate);
protein Icd(isocitrate --> keto-glutarate);
//protein AceK(Icd <--> Icd@phosphate);
protein SucA(keto-glutarate --> succinyl-CoA);
protein SucD(succinyl-CoA --> succinate);
//protein SucA, SucB, SucD, SucC;
protein Sdh(succinate --> fumarate);
//protein SdhA(succinate --> fumarate);
//        SdhB(succinate --> fumarate), 
//        SdhC(succinate --> fumarate),          
//        SdhD(anchor), 
//        SdhE(succinate --> fumarate);
protein FumA(fumarate --> malate);
//protein FumA(), FumB(an), FumC, FumD, FumE;
protein Mdh(malate --> oxaloacetate);
//protein_complex Sdh = SdhA + SdhB + SdhC + SdhD + SdhE;

//pathway TCA = GltA --> AcnA | AcnB --> Icd --> SucA + SucB --> SucD + SucC --> Sdh --> FUM --> Mdh; 
pathway TCA = GltA --> AcnA --> Icd --> SucA --> SucD --> Sdh --> FumA --> Mdh; 
//@```
//@
