// BSD 3-Clause License
// © 2022, The University of Texas Southwestern Medical Center. All rights reserved.
// Donghoon M. Lee and Daehwan Kim

// EFs: elongation factors

// CP: changed to _
protein EF_Tu // Binds GTP; bring Aminoacyl-tRNA to A-site of ribosome
{
    reaction TernaryComplexFormation(self~GTP + AA-tRNA --> self~GTP~AA-tRNA, Kd=1e-9);
}

// CP: changed to _
protein EF_Ts // Generates EF-Tu
{
    reaction TsToGTPSwap(EF-Tu~self + GTP --> EF-Tu~GTP + self, Kd=1e-9);
    reaction GDPToTsSwap(EF-Tu~GDP + self --> EF-Tu~self + GDP, Kd=1e-9);
}

// CP: changed to _
protein EF_G // Helps in translocation of ribosome
{
    reaction GTPLoading(self + GTP --> self~GTP, Kd=1e-9);
    reaction GDPtoGTPExchange(self~GDP + GTP --> self~GTP + GDP, Kd=1e-9);
}

// CP: changed to _
EF_Tu = 5nM;
EF_Ts = 5nM;
EF_G = 5nM;
