// Donghoon M. Lee, Austin Marckx, and Daehwan Kim
// IFs: initiation factors

protein IF1; // Helps to stabilize 30S ribosomal subunit
protein IF2 // Binds fmet-tRNA with 30S subunit mRNA complex; bind GTP and hydrolyse
{
    // IF2 GTP loading and recycling
    reaction GDPLoading(self + GDP --> self~GDP, Kd=1e-9);
    reaction GDPtoGTPExchange(self~GDP + GTP --> self~GTP + GDP, Kd=1e-9);

    // Note: IF2~GTP hydrolysis occurs in 70S preinitiation complex, hence is written in Ribosome.lp
}
protein IF3; // Binds 30S subunit with mRNA

IF1 = 5nM;
IF2 = 5nM;
IF3 = 5nM;