// BSD 3-Clause License
// © 2022, The University of Texas Southwestern Medical Center. All rights reserved.
// Donghoon M. Lee and Daehwan Kim

// Translation

// Translation in Prokaryotes
// Marina V Rodnina
// Cold Spring Harb Perspect Biol. 2018 Sep 4;10(9):a032664.
// https://cshperspectives.cshlp.org/content/10/9/a032664.long

import Ribosome;

Ribo_30S = Ribosome.Ribo_30S;
Ribo_50S = Ribosome.Ribo_50S;
Ribo_70S = Ribosome.Ribo_70S;
AA_tRNASynthetase = Ribosome.AA_tRNASynthetase;

pathway Translation
{
    reaction Initiation
    {
        InitialtRNAloading = Ribo_30S.InitialtRNAloading;
        Complexation = Ribo_70S.Complexation;
    }
    
    reaction Elongation
    {
        CodonRecognition = Ribo_70S.CodonRecognition;
        PeptidylTransfer = Ribo_70S.Elongation.PeptidylTransfer;
        RNATranslocation = Ribo_70S.Elongation.RNATranslocation;
    }

    // Step 3. Termination: see Ribosome
    reaction Termination 
    {
        StopCodonRecognition = Ribo_70S.StopCodonRecognition;
        PeptideRelease = Ribo_70S.PeptideRelease;
        Dissociation = Ribo_70S.Dissociation;
    }

    tRNACharging = AA_tRNASynthetase.tRNACharging;

    Ribo_30S = 50000;
    Ribo_50S = 50000;

    IF = 10000;
    EF_Tu = 443852; // tufA
    EF_G = 86623; // fusA
    RF = 2000; 
    RRF = 8329; // frr

    tRNA = 375000;
    AA = 90mM;
    AA_tRNASynthetase = 87102;
}

reference ThomasSteitz_2008
{
    title = "A structural understanding of the dynamic ribosome machine";
    doi = "https://doi.org/10.1038/nrm2352";
}
