// BSD 3-Clause License
// © 2023, The University of Texas Southwestern Medical Center. All rights reserved.
// Donghoon M. Lee and Daehwan Kim

// Amino acid Synthesis

from MetaboliteConcentrations import *;

float rate_as = EcoliInfo.ProteinSynthesisRate * EcoliInfo.C2M;

pathway AASynthesis
{
    reaction GlutamineSynthesis(G6P -> glutamine) // G6P is a placeholder
    specification
    {
        glutamine' = rate_as;
    }
}
