// BSD 3-Clause License
// © 2023, The University of Texas Southwestern Medical Center. All rights reserved.
// Donghoon M. Lee and Daehwan Kim

// Glucose Metabolism

from MetaboliteConcentrations import *;

import MetaboliteConcentrations;
// import GlucoseTransport;
import Glycolysis;
import PyruvateOxidation;
import CitrateCycle;
import NADH_OxidativePhosphorylation;
import FADH2_OxidativePhosphorylation;
import EnergyConsumption;

pathway CentralCarbonMetabolism
{
    membrane CellMembrane
    {
        // GlucoseTransporter = GlucoseTransport.GlucoseTransport;

        cytosol Cytosol
        {
            Glycolysis = Glycolysis.Glycolysis;
            PyruvateOxidation = PyruvateOxidation.PyruvateOxidation;
            CitrateCycle = CitrateCycle.CitrateCycle;
            NADH_OxidativePhosphorylation = NADH_OxidativePhosphorylation.NADH_OxidativePhosphorylation;
            FADH2_OxidativePhosphorylation = FADH2_OxidativePhosphorylation.FADH2_OxidativePhosphorylation;
            EnergyConsumption = EnergyConsumption.EnergyConsumption;

            G6P[:] = MetaboliteConcentrations.G6P;
        }
    }
}

reference KimGadd_2008   // ATP requirements for polymer synthesis in E coli.
{
    title = "Bacterial Physiology and Metabolism.";
    page = "191";
    table = "6.10";
    page += "192";
    table += "6.11";
} 

// Table 6.10. ATP requirement for polymer synthesis by Escherichia coli using glucose–mineral salts medium
// Polymer  ATP required for the synthesis of polymer to make up one gram dry wt cell material (mmol/g dry wt)
//
// Polysaccharide   2.1
//
// Protein
// Glucose to amino acids   1.4
// Polymerization (translation) 19.1
//
// Lipid    0.1
//
// RNA
// Glucose to ribonucleotides   3.5
// Polymerization (transcription)   0.9
//
// DNA
// Glucose to deoxyribonucleotides  0.9
// Polymerization   0.2
//
// Transport    5.2
// 
// RNA turnover 1.4
//
// Overall  34.8
//
