// BSD 3-Clause License
// © 2023, The University of Texas Southwestern Medical Center. All rights reserved.
// Donghoon M. Lee and Daehwan Kim

// Citrate Cycle

import * from EcoliInfo;
import * from MetaboliteConcentrations;

pathway CitrateCycle(acetyl_CoA + 3 NAD + FAD + ADP --> CoA_SH + 3 NADH + FADH2 + ATP)
specification
{
    float Init_AcetylCoA = 0.61mM;
    ATP' = acetyl-CoA / (Init_AcetylCoA + acetyl-CoA) * EGM_TCACycle_Sec;
}
