// BSD 3-Clause License
// © 2023, The University of Texas Southwestern Medical Center. All rights reserved.
// Donghoon M. Lee and Daehwan Kim

// FADH2 Oxidative Phosphorylation

from MetaboliteConcentrations import *;

import MetaboliteConcentrations;
import EcoliInfo;

pathway FADH2_OxidativePhosphorylation(2 FADH2 + 3 ADP -> 2 FAD + 3 ATP)
specification
{
    ATP' = FADH2 / (MetaboliteConcentrations.FADH2 + FADH2) * EcoliInfo.EGM_OxidativePhosphorylation_FADH2_Sec;
}
