// BSD 3-Clause License
// © 2023, The University of Texas Southwestern Medical Center. All rights reserved.
// Donghoon M. Lee and Daehwan Kim

// FADH2 Oxidative Phosphorylation

import * from EcoliInfo;
import * from MetaboliteConcentrations;

pathway FADH2_OxidativePhosphorylation(FADH2 + 1.5 ADP -> FAD + 1.5 ATP)
specification
{
    float Init_FADH2 = 0.5mM;
    ATP' = FADH2 / (Init_FADH2 + FADH2) * EGM_OxidativePhosphorylation_FADH2_Sec;
}
