// BSD 3-Clause License
// © 2023, The University of Texas Southwestern Medical Center. All rights reserved.
// Donghoon M. Lee and Daehwan Kim

// Pyruvate sOxidation

import * from EcoliInfo;
import * from MetaboliteConcentrations;

reaction PyruvateOxidation(pyruvate + NAD + CoA-SH -> acetyl-CoA + NADH)
specification
{
    float Init_Pyruvate = 0.39mM;
    acetyl-CoA' = pyruvate / (Init_Pyruvate + "pyruvate") * EGM_Pyruvate_Sec;
}
